In [27]:
import numpy as np
import pandas as pd
import nibabel as nib
from scipy import io as sio
from scipy import cluster as scl

In [2]:
stack_path = '/data1/subtypes/serial_preps/netstack_dmn_rmap_part_site_279_sample_scale_007.npy'
mask_path = '/data1/abide/Mask/mask_data_specific.nii.gz'

In [3]:
m_img = nib.load(mask_path)
mask = m_img.get_data().astype(bool)
stack = np.load(stack_path)

In [4]:
stack.shape

(7, 45309, 279)

In [5]:
out_path = '/data1/abide/legacy_test/mean_centered_old1.nii.gz'
old_1 = np.zeros_like(mask, dtype=float)
old_1[mask] = stack[0,:,0]

old_img = nib.Nifti1Image(old_1, header=m_img.get_header(), affine=m_img.get_affine())
nib.save(old_img, out_path)

In [8]:
# Look at similar data
comp_data = '/data1/abide/legacy_test/data/test_sub.csv'

In [12]:
comp = pd.read_csv(comp_data, header=None)

In [15]:
cp = comp.as_matrix()

In [16]:
cp.shape

(3, 45309)

In [17]:
cp[0,0:4]

array([-0.13216 , -0.019897,  0.062423,  0.033379])

In [18]:
a = np.corrcoef(cp)

In [19]:
a.shape

(3, 3)

In [20]:
a

array([[ 1.        ,  0.00574239,  0.17181583],
       [ 0.00574239,  1.        ,  0.03472632],
       [ 0.17181583,  0.03472632,  1.        ]])

In [21]:
cmat = sio.loadmat('/data1/abide/legacy_test/subtype/sc7/diag_mean_maybe/network_1/network_1_stack.mat')

In [22]:
cpt = cmat['stack']

In [23]:
cpt.shape

(279, 45309)

In [24]:
R = np.corrcoef(cpt)

In [25]:
R.shape

(279, 279)

In [26]:
R[0,:10]

array([ 1.        ,  0.0057425 ,  0.17181583,  0.0721314 ,  0.04166047,
       -0.05893246,  0.0177503 ,  0.00496642,  0.16694319, -0.17590848])

In [28]:
link_mat = scl.hierarchy.linkage(R , method='ward')

In [29]:
order = np.array(scl.hierarchy.dendrogram(link_mat, no_plot=True, get_leaves=True)['leaves'])

In [30]:
order[:10]

array([ 23, 116, 224,  24,  25, 252, 278, 232,  35, 174])

In [31]:
part = scl.hierarchy.fcluster(link_mat, 5, criterion='maxclust')

In [34]:
np.where(part==5)[0]+1

array([  1,   2,   8,  19,  31,  44,  46,  47,  51,  53,  55,  65,  66,
        69,  73,  77,  83,  85,  87,  95,  98, 102, 103, 106, 109, 110,
       112, 118, 122, 123, 124, 130, 135, 136, 142, 143, 148, 169, 171,
       172, 174, 176, 179, 180, 182, 184, 186, 192, 196, 198, 199, 200,
       201, 202, 203, 204, 205, 207, 209, 211, 212, 213, 215, 216, 217,
       218, 219, 223, 224, 227, 228, 231, 232, 237, 244, 245, 250, 252,
       256, 259, 266, 268, 270, 272, 276, 278])

In [35]:
rr = np.around(R, 4)

In [37]:
r_link = scl.hierarchy.linkage(rr, method='ward')

In [39]:
r_order = np.array(scl.hierarchy.dendrogram(r_link, no_plot=True, get_leaves=True)['leaves'])

In [40]:
r_part = scl.hierarchy.fcluster(r_link, 5, criterion='maxclust')

In [41]:
r_part[:4]

array([5, 5, 4, 4], dtype=int32)

In [42]:
np.where(r_part==5)[0]+1

array([  1,   2,   8,  19,  31,  44,  46,  47,  51,  53,  55,  65,  66,
        69,  73,  77,  83,  85,  87,  95,  98, 102, 103, 106, 109, 110,
       112, 118, 122, 123, 124, 130, 135, 136, 142, 143, 148, 169, 171,
       172, 174, 176, 179, 180, 182, 184, 186, 192, 196, 198, 199, 200,
       201, 202, 203, 204, 205, 207, 209, 211, 212, 213, 215, 216, 217,
       218, 219, 223, 224, 227, 228, 231, 232, 237, 244, 245, 250, 252,
       256, 259, 266, 268, 270, 272, 276, 278])